### ISSUE TITLE
Panic when trying to get feed

### ISSUE THREAD

**Issue by ghost** [lmas/feedloggr#3]
This specific RSS feed throws an error when trying to access it:
https://www.youtube.com/feeds/videos.xml?channel_id=UCl2mFZoRqjw_ELax4Yisf6w

Full stack trace:
```
❯ feedloggr
2021/02/10 15:11:10 Updating Louis Rossmann (https://www.youtube.com/feeds/videos.xml?channel_id=UCl2mFZoRqjw_ELax4Yisf6w)
panic: runtime error: index out of range [100] with length 100


goroutine 1 [running]:
github.com/lmas/Damerau-Levenshtein.(*TrueDamerauLevenshtein).Distance(0xc000166f30, 0xc00022b500, 0x63, 0xc0003835c0, 0x25, 0x9f6860)
        /home/spiral/go/src/github.com/lmas/Damerau-Levenshtein/damerau-levenshtein.go:72 +0x710
github.com/lmas/Damerau-Levenshtein.Distance(...)
        /home/spiral/go/src/github.com/lmas/Damerau-Levenshtein/damerau-levenshtein.go:24
github.com/lmas/feedloggr/pkg.seenTitle(0xc00022b500, 0x63, 0xc0001d0700, 0xd, 0x10, 0x30)
        /home/spiral/go/src/github.com/lmas/feedloggr/pkg/internal.go:45 +0x85
github.com/lmas/feedloggr/pkg.(*App).newItems(0xc0001dc2c0, 0xc00017e2d0, 0x4c, 0x2, 0x2, 0xc0001dbc08, 0x11, 0x0)
        /home/spiral/go/src/github.com/lmas/feedloggr/pkg/internal.go:71 +0x165
github.com/lmas/feedloggr/pkg.(*App).updateAllFeeds(0xc0001dc2c0, 0xc000167170, 0xd6dec0, 0x0, 0x0)
        /home/spiral/go/src/github.com/lmas/feedloggr/pkg/internal.go:98 +0x1cc
github.com/lmas/feedloggr/pkg.(*App).Update(0xc0001dc2c0, 0xc0001dc2c0, 0x0)
        /home/spiral/go/src/github.com/lmas/feedloggr/pkg/feedloggr.go:83 +0x4c
main.main()
        /home/spiral/go/src/github.com/lmas/feedloggr/cmd/feedloggr/feedloggr.go:58 +0x3e5
```

**Comment by lmas** [comment]
Oh wow, so exciting to see someone else use this tiny tool! And thanks so much for your report!

I just tried it myself:
```
$ go run cmd/feedloggr/feedloggr.go -verbose
2021/02/10 16:36:49 Updating test (https://www.youtube.com/feeds/videos.xml?channel_id=UCl2mFZoRqjw_ELax4Yisf6w)
2021/02/10 16:36:51 Generating page...
2021/02/10 16:36:51 Writing page to tmp/news/2021-02-10.html...
```
but it didn't panic like it did for you.

 Really interesting it was a panic from my `damerau-levenshtein` pkg. Could you try it again? And if it panics yet again, could you pretty please try and download that page (for example with `wget "url"`) and try upload it somewhere for me so I could test it too?

**Comment by ghost** [comment]
Hi! Thanks for your quick answer!
Yes, it still panics. Here's the feed dump: https://spiral.sh/files/UCl2mFZoRqjw_ELax4Yisf6w.txt

By the way, I am very happy to have found feedloggr. It does exactly what I want, how I would want it to. Really nice software :D

**Comment by lmas** [comment]
Aww man thanks a lot for your kind words :'D 

Just checked it, I thought at first it was some YT region thingy messing around in the feed but it's basically no diffs from my end. Looking at the source there's some titles for the feed items that are longer than 100 chars and the `damerau-levenshtein` pkg defaults to 100 chars max limit (whoops that's a too short hardcoded limit). Really weird it doesn't panic for me though, might be ghosts with my own setup..

Imma have to go investigate it on my end this weekend, when I have more time left over (sorry) and can do some more thorough testing.

**Comment by lmas** [comment]
Aww heck can't leave you hanging until the weekend, so I made a super dirty quickfix until then. You can try updating your source and run it against that feed again, hopefully confirming my hypothesis

**Comment by ghost** [comment]
That did fix it, thanks~

**Comment by lmas** [comment]
Fixed the buggy dependency so it should be all good now
